version: "3"
services:
  squid:
    # image: sameersbn/squid:3.5.27-2
    build: ./squid/
    container_name: squid
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - ./squid/cache:/var/spool/squid
      - ./squid/squid.conf:/etc/squid/squid.conf
